### ISSUE TITLE
GPIO config/changing

### ISSUE THREAD

**Issue by darkside9009** [rednblkx/HomeKey-ESP32#104]
Hi, 
I have my own hardware with ESP32 with some connectors (outside). Is it possible to change the GPIOs config for MOSI, MISO, SCK and SS pin?

Best,
Darius

**Comment by rednblkx** [comment]
Hi,

Yes, you have to compile the project, see [line 32](https://github.com/rednblkx/HomeKey-ESP32/blob/4c9930cf9e3103d15bde7fdd1cc74c607c896dab/src/main.cpp#L32) to change the pins.
