### ISSUE TITLE
Ethernet

### ISSUE THREAD

**Issue by yannik2480** [rednblkx/HomeKey-ESP32#113]
Is Ethernet support with WT32 ETH01 working or is it still in progress? Also is it possible in anyway with Ethernet?

**Comment by rednblkx** [comment]
No, there is no Ethernet support, but, someone did make the modifications for WT32-ETH01, see https://github.com/rednblkx/HomeKey-ESP32/issues/48#issuecomment-2299256180, though can't say i have tested this
