### ISSUE TITLE
Re-configure WiFi hotspot

### ISSUE THREAD

**Issue by LiYanan2004** [rednblkx/HomeKey-ESP32#122]
Is there a way to re-configure the Wi-Fi instead of re-flash the firmware to get it reset to factory settings.

**Comment by rednblkx** [comment]
The base library HomeSpan has a "Device Configuration Mode" accessible through a button but there is not GPIO pin set by default and unless you did set one up on the web interface, you'll have to either configure wifi trough the serial terminal or just erase and re-flash.

**Comment by LiYanan2004** [comment]
Thanks for you reply!
