### ISSUE TITLE
FYI: PN532 not found? Could be bad trace.

### ISSUE THREAD

**Issue by spdustin** [rednblkx/HomeKey-ESP32#124]
For those having problems with the PN532 not being detected, my (brand name) board had a bad trace from the SS pin to the fourth resistor down on the board (see photo)

I had to (carefully) solder on a small bit of AWG30 between the soldered pin header and the right side of the resistor.

It's worth unplugging the board and using your favorite multimeter to check continuity (assuming 8-pin header is on the right) between `SCK`, `MISO`, `MOSI`, `SS`, and `IRQ` solder joints and the right-side of the resistors. Bonus points for checking continuity between `RSTQ` and the fifth pin from the top right on the PN532 itself.

![CleanShot 2024-09-07 at 14 28 15@2x](https://github.com/user-attachments/assets/ae9df697-8233-4201-a85f-2d6e3ef18b2e)

**Comment by rednblkx** [comment]
Thanks for sharing this, I’ll pin it so others will see it until I add it to the wiki.
