### ISSUE TITLE
error backtrace

### ISSUE THREAD

**Issue by pilot1981** [rednblkx/HomeKey-ESP32#132]
5910 0x400D4AFB:0x3FFC5930

E (58641) task_wdt: Print CPU 1 backtrace

Backtrace: 0x400825D5:0x3FFB1A60 0x4008392D:0x3FFB1A80 0x4000BFED:0x3FFC36F0 0x4008BB87:0x3FFC3700 0x4008A672:0x3FFC3720 0x4013085E:0x3FFC3760 0x40131A21:0x3FFC3790 0x40131AC9:0x3FFC37B0 0x40132211:0x3FFC37D0

I (63705) MAIN: mqtt_connected_event > MQTT connected
E (79044) MQTT_CLIENT: mqtt_message_receive: transport_read() error: errno=128
E (79045) MQTT_CLIENT: mqtt_process_receive: mqtt_message_receive() returned -1
I (94070) MAIN: mqtt_connected_event > MQTT connected
E (109355) MQTT_CLIENT: mqtt_message_receive: transport_read() error: errno=128
E (109356) MQTT_CLIENT: mqtt_process_receive: mqtt_message_receive() returned -1
I (124720) MAIN: mqtt_connected_event > MQTT connected
E (139885) MQTT_CLIENT: mqtt_message_receive: transport_read() error: errno=128
E (139886) MQTT_CLIENT: mqtt_process_receive: mqtt_message_receive() returned -1
E (147290) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (147290) task_wdt:  - IDLE1 (CPU 1)
E (147290) task_wdt: Tasks currently running:
E (147290) task_wdt: CPU 0: IDLE0
E (147290) task_wdt: CPU 1: loopTask
E (147290) task_wdt: Print CPU 0 (current core) backtrace

Backtrace: 0x4014C1FA:0x3FFB1460 0x4008392D:0x3FFB1480 0x401F361B:0x3FFC04B0 0x4014C8F5:0x3FFC04D0 0x4008AC4C:0x3FFC04F0

E (147290) task_wdt: Print CPU 1 backtrace

Backtrace: 0x400825D5:0x3FFB1A60 0x4008392D:0x3FFB1A80 0x4000BFED:0x3FFC36F0 0x4008CB5F:0x3FFC3700 0x4008A770:0x3FFC3720 0x4013085E:0x3FFC3760 0x40131A21:0x3FFC3790 0x40131AC9:0x3FFC37B0 0x40132211:0x3FFC37D0

I (154922) MAIN: mqtt_connected_event > MQTT connected
E (160129) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (160129) task_wdt:  - IDLE1 (CPU 1)
E (160129) task_wdt: Tasks currently running:
E (160129) task_wdt: CPU 0: IDLE0
E (160129) task_wdt: CPU 1: loopTask
E (160129) task_wdt: Print CPU 0 (current core) backtrace

Backtrace: 0x4014C1FA:0x3FFB1460 0x4008392D:0x3FFB1480 0x401F361B:0x3FFC04B0 0x4014C8F5:0x3FFC04D0 0x4008AC4C:0x3FFC04F0

E (160129) task_wdt: Print CPU 1 backtrace

Backtrace: 0x400825D5:0x3FFB1A60 0x4008392D:0x3FFB1A80 0x4000BFED:0x3FFC36F0 0x4008CB5F:0x3FFC3700 0x4008A770:0x3FFC3720 0x401

**Comment by rednblkx** [comment]
MQTT looks to be struggling maintaining a connection and is consuming cpu cycles. This could either be a bad board or just spotty WiFi connection which could be derived from a bad chip.
