### ISSUE TITLE
[Feature Request] - Wifi RSSi

### ISSUE THREAD

**Issue by electric-m** [rednblkx/HomeKey-ESP32#134]
Hey there,

woul dit be possible to integrate the strength of the Wifi connection in the Web UI?
Just some Text like "Signal: -67 dBi" or similar.

Michael

**Comment by rednblkx** [comment]
Hi there!

Yes, that would actually be a good idea considering the fact that WiFi seems to be common issue, thanks.

Also, thanks for the donation, appreciate it ❤️

**Comment by rednblkx** [comment]
Added in [v0.4.1](https://github.com/rednblkx/HomeKey-ESP32/releases/tag/v0.4.1)
