### ISSUE TITLE
1 out of 2 home devices fails to utilize express mode.

### ISSUE THREAD

**Issue by ihrapsa** [rednblkx/HomeKey-ESP32#14]
The latest build has issues when polling the HomeKey on my **iPhone 12 Pro iOS 17.0**. My partner's **iPhone 15 Pro Max iOS 17.3** has no issue with Express mode. I tried pairing it from both of our devices. I erased ESP32 flash multiple times. I rebooted phone, but issue persisted.

Looking at the logs I get:
at the beginning when pairing the lock:
```
Starting HAP Server on port 80 supporting 9 simultaneous HomeKit Controller Connections...

DEVICE NOT YET PAIRED -- PLEASE PAIR WITH HOMEKIT APP
[...]
*** ERROR: Unrecognized Controller PairingID
```

Then when approaching the reader I get:

```
I (284881) LockMechanism: *** PASSIVE TARGET DETECTED ***
```
This is the same behavior as when I'm approaching a random NFC card. However, using the HomeKey in the Wallet the authentication succeeds.

Any idea what's going on? 
I can't seem to change the log level. It said it's on Level 2 but I see no difference from level 0. I'm starting to wonder if the issue is with my phone, however Express Mode works in other circumstances (with transit cards)

**Comment by rednblkx** [comment]
This might be caused by the filter i added to identify a homekey early as i've seen that all devices be it an iPhone or a Watch have ATQA 0x04 and SAK 0x20 which thinking about it now is not exactly needed since sending a SELECT command for the HomeKey Applet is enough and based on the response we can rule out the target as homekey.

**Comment by ihrapsa** [comment]
Latest dev branch fixes this. Awesome! 😎 
I guess we can close this issue.

**Comment by rednblkx** [comment]
Brilliant 🥳, glad that helped. 
Note that you can just ignore the “Unrecognized Controller PairingID”, that’s just a device that is trying to connect to the accessory with the wrong authorization, that might happen when you add a device after you previously removed it or just a device in home that hasn’t paired yet.
Also logs are a bit segregated at the moment, HomeSpan has it’s own log system and I’m just using the integrated logging from esp-idf for all the home key stuff and I added the command `@L` followed by the level name to change log level (N,I,D or V).
