### ISSUE TITLE
After Reflashing the esp32 I can't add it to HomeKit Anymore

### ISSUE THREAD

**Issue by 343max** [rednblkx/HomeKey-ESP32#151]
After erasing the flash and reflashing the esp32 I can't add the HomeKey anymore to the Home App.

After entering the setup code the process will just time out after a while. The error message reads "device can't be reached".

![image](https://github.com/user-attachments/assets/720b63ff-c5ed-47ac-b8e2-9c5049e196b2)

**Comment by misc2000** [comment]
I have had a similar issue some days ago.
Did you already try to reset the HomeKit ID in the web config interface of the ESP?

**Comment by rednblkx** [comment]
If you erased the flash make sure it's reconnected to wifi.
If you still have issues, hook it to a serial terminal, use the `L2` command, try to add it to Home and post the logs (make sure to truncate the data).

**Comment by 343max** [comment]
Sorry, forgot to close this. What seems to have fixed it was to rename the esp32 HomeKey so it was different from the name it had before.
