### ISSUE TITLE
IP connectivity (ping) lost - hibernation?

### ISSUE THREAD

**Issue by net47** [rednblkx/HomeKey-ESP32#160]
I just flashed v0.5 on my ESP32 and configured everything successfully. The ESP32 is powered via USB cable to my notebook, so constant power source. Unfortunately, after a few minutes (5 I guess) connectivity (tested via ping and http) is lost and only restored after unplugging USB and pluggin in again. 

Is there some sort of hibernation mode active? I didn't find any setting in the WebUI tbh.

**Comment by adukale** [comment]
This happened with me when ESP32 was not getting enough power. Can you try powering using USB wall charger?

**Comment by net47** [comment]
> This happened with me when ESP32 was not getting enough power. Can you try powering using USB wall charger?

I now plugged it into my iPad charger and et voilà, it's running without any noticable ping-lost. Thanks for the tip!

**Comment by net47** [comment]
PEBCAK, works with the correct power supply.
