### ISSUE TITLE
Clicking buttons in UI -> "not found"

### ISSUE THREAD

**Issue by SentiQ** [rednblkx/HomeKey-ESP32#161]
After OTA Update from 0.4.1 to 0.5 I get these:

![grafik](https://github.com/user-attachments/assets/ee553d8b-1b1a-44c8-a8e8-eb3fa2c3ef62)

Tried it 3 times - cleared caches, used other browser etc.

**Comment by adukale** [comment]
I might be wront but this seems life littlefs issue.
Can you check if you executed command like below for littlefs.bin after firmware.bin ota?
`espota.py -r -i 192.168.1.12 -a homespan-ota -s -f .pio/build/c3/littlefs.bin`
Try executing ota with above command for littlefs.bin.
