### ISSUE TITLE
Not publishing RFID Cards

### ISSUE THREAD

**Issue by Z-pi** [rednblkx/HomeKey-ESP32#21]
Thank you for making this awesome project, it's working perfectly with my Apple devices and publishing the data to MQTT. I just have one problem the esp32 is not publishing the UID or any other information when reading a passive card. The log shows the UID but it is not published to the MQTT "Auth" topic. Is there something I need to activate to get this to work?
![Screenshot 2024-02-11 at 15 08 23](https://github.com/rednblkx/HomeKey-ESP32/assets/25182652/2a6605a7-b00a-459f-89a6-e46910c44b0e)
![Screenshot 2024-02-11 at 15 08 38](https://github.com/rednblkx/HomeKey-ESP32/assets/25182652/bad1d6cb-bb57-46b5-8ac2-3d5f995325d9)

**Comment by rednblkx** [comment]
yeah, i messed on conditionals, i pushed some changes now, please let me know if this fixes it

**Comment by Z-pi** [comment]
Thank you! that fixed it, Suggestion for HASS users that want tags to appear in native HASS tags, send the below json to homeassistant/tag/voordeur/front-door-rfid/config 
`{
  "topic": "topic/auth", 
  "value_template": "{{ value_json.uid }}",
  "device":{
    "name":"Voordeur RFID",
    "identifiers":[
         "frontdoorrfid"
       ]
    
  }
}`

**Comment by rednblkx** [comment]
That’s cool, might use it, thank you. Never really bothered to read how tags work in HASS. I should create a wiki at some point to add stuff like this.
