### ISSUE TITLE
Module recommendation?

### ISSUE THREAD

**Issue by segdy** [rednblkx/HomeKey-ESP32#63]
I know Elechouse V3 is recommended but this doesn’t seem to exist any more. But here is V4. Is this the recommended version now?

https://www.elechouse.com/product/pn532-nfc-rfid-module-v4/

the only thing is this is nearly 40$ with shipping. On the other hand. There are 10$ versions from HiLetgo and Waveshare on Amazon. Are these 2 not “trustworthy”? Elechouse is not on Amazon.

If I may have any issues with HiLetgo or Waveshare I’d just bite the bullet and pay the 40$ and order from Elechouse site directly. But wanted to check first if this is even the recommended adapter.

**Comment by jess-sys** [comment]
I had some of those : https://aliexpress.com/item/1005005973913526.html and I can confirm it's working properly.

**Comment by segdy** [comment]
Awesome, thanks!
Ordered!
Hopefully sufficient for my first tests.

**Comment by rednblkx** [comment]
You can use any module that has a PN532 chip,  however, most if not all $10 modules have a bad range as they are a cheap clone of Elechouse’s design.

In spite of that, recently made some discoveries that should hopefully aid with that, you can, for more information you can follow see this [comment](https://github.com/rednblkx/HomeKey-ESP32/issues/62#issuecomment-2155123109) in issue #62 and subsequent comments after

**Comment by segdy** [comment]
Thanks!! I’ll just start with the one from @jess-sys (already ordered) for playing around.

When I hit issues I’ll get the 40$ one … and when I permanently install it on my door I want something solid anyway l.

**Comment by x23piracy** [comment]
14€ https://www.amazon.de/dp/B0B1QB4347?psc=1&ref=ppx_yo2ov_dt_b_product_details
