### ISSUE TITLE
cant compile

### ISSUE THREAD

**Issue by thorsten-gehrig** [rednblkx/HomeKey-ESP32#7]
Hi 
currently i´ll get the following issue:
```
src/main.cpp: In member function 'virtual void LockMechanism::loop()':
src/main.cpp:156:109: error: no matching function for call to 'PN532::readPassiveTargetID(int, uint8_t [16], uint8_t*, uint16_t [1], uint8_t [1], int, bool)'
```
Do you see the same?
Best
Thorsten

**Comment by rednblkx** [comment]
Hi Thorsten,

I did some minor changes to the PN532 library to be able to collect atqa and sak values, just have PlatformIO update the dependencies with `pio pkg update`.
