### ISSUE TITLE
Feature Request subscribed topics for active led and buzzer

### ISSUE THREAD

**Issue by leschNUX** [rednblkx/HomeKey-ESP32#70]
Hello,
I have a request for an extension. You can also subscribe to topics and activate the switching of the led and the buzzer there.

Example:
The garage door goes up, and the LED flashes and the buzzer beeps every few seconds.

**Comment by rednblkx** [comment]
Hello!

So...basically a GPIO Pin that you can control from an MQTT topic? This was previously suggested in #57, however, i don't currently see this fit with this project.

This is one of the reasons why i'm actually working on a ESPHome version, it would make much more sense than to start baking in a bunch of automation stuff in this project.
