### ISSUE TITLE
Always unlock needs fixing

### ISSUE THREAD

**Issue by ar0903** [rednblkx/HomeKey-ESP32#76]
https://github.com/rednblkx/HomeKey-ESP32/blob/849957ecb18f225973a7f52afce429a2d8f5b55a/src/main.cpp#L1037C1-L1038C12

The closing curly brace '}' should move up before the 'else if'
Otherwise, lock always happens after auto unlock.

**Comment by rednblkx** [comment]
Not sure how that happened but thanks for the heads up, now fixed in dev, will be released shortly as a small update alongside other things.
