### ISSUE TITLE
firmware_ota.bin

### ISSUE THREAD

**Issue by tukkatakka** [rednblkx/HomeKey-ESP32#80]
Hello, 

where can I find the update file "firmware_ota.bin"? 
Or do I have to rename the file "firmware_merged.bin" to "firmware_ota.bin"? 

Thank you 

Thanks already, a great project!

**Comment by rednblkx** [comment]
`firmware.bin` was meant to be `firmware_ota.bin` but never renamed it and forgot to update wiki.
