### ISSUE TITLE
Question: what’s the thickness of door the signal can go through 

### ISSUE THREAD

**Issue by haupthakan** [rednblkx/HomeKey-ESP32#91]
I was wondering if it’s possible to stick the nfc module to my door and toggle it that way.
Of course it won’t work if it’s a metal door. 
mine is plain wood but pretty thick and massive.  
had anyone luck with it?

thanks for this cool project :)

**Comment by rednblkx** [comment]
i believe someone on the discord server might've tried that, you can join in and ask. 

Ideally, the antenna on the red board you usually find should have about 5-6 cm if it actually has the right capacitors.
