### ISSUE TITLE
Lock not showing up in Home App after deleting

### ISSUE THREAD

**Issue by soldmike** [rednblkx/HomeKey-ESP32#92]
Thank you very much for your project. The installation was going easy with your documentation.
I got it up and running quite fast. But then I made the (maybe stupid) mistake to delete it from the Home App, because I wanted to change the card finish and it didn‘t update.

So now I have the ESP deleted from the Home App, but it does not show up to add again. My guess is, that the HomeKey still thinks that it is connected to the Home App. Is there an easy way to reset that, or do I have to do the installation all over again?

Do you need any further information?
Thank you for your help

**Comment by niiccooo1** [comment]
I would erase and reflash the esp

**Comment by rednblkx** [comment]
Sometimes, the iPhone would ignore the device after being removed and would start to appear after some time, not sure if it's a bug in HomeSpan or something in HomeKit.

If you haven't yet mounted it somewhere, just erase it with `esptool.py erase_flash` and flash again so it can generate new ID.
