### ISSUE TITLE
No Wifi - AP

### ISSUE THREAD

**Issue by Wolf6660** [rednblkx/HomeKey-ESP32#93]
hi, i flash the firmware on a wemos D1 mini with this command:

 esptool.py --port /dev/cu.usbserial-11110 write_flash 0x0 ~/Downloads/esp32-firmware_merged.bin

Serial port /dev/cu.usbserial-11110
Connecting....
Detecting chip type... Unsupported detection protocol, switching and trying again...
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 08:f9:e0:75:a1:f1
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Flash will be erased from 0x00000000 to 0x003fffff...
Compressed 4194304 bytes to 1064615...
Wrote 4194304 bytes (1064615 compressed) at 0x00000000 in 107.3 seconds (effective 312.6 kbit/s)...
Hash of data verified.

and than i dont have a accesspoint. Why?

I tested 2 Wemos D1 mini

**Comment by rednblkx** [comment]
Please pay attention to the [prerequisites](https://github.com/rednblkx/HomeKey-ESP32/wiki/Prerequisites#hardware-and-software) before jumping to flash stuff. 

The board you are using has an ESP8266 chip which is a different chip from the ESP32 required for this and not at all supported by the ESP-IDF framework.

I understand there might be a confusion with the board name, “wemos d1 mini” or “d1 mini” is also being used for boards with an ESP32 and all vendors will have that mention.
