### ISSUE TITLE
Question: Issues with HomeKey Support on iOS 18

### ISSUE THREAD

**Issue by kh2901** [rednblkx/HomeKey-ESP32#94]
Thank you for your implementation. Currently I am evaluating an installation behind my doorbell. Has anyone experienced issues with the HomeKey functionality after upgrading to iOS 18?

**Comment by thorsten-gehrig** [comment]
Works still fine with ios18 and 18.1 betas. 

Best
Thorsten

**Comment by kh2901** [comment]
Thank you for fast response ✌🏽
