### ISSUE TITLE
Not responding as soon as added in Home app

### ISSUE THREAD

**Issue by davidgrdm** [rednblkx/HomeKey-ESP32#98]
Hi everyone, 
As soon as I add my ESP32 to the Home app on iOS, it became unresponsive  "Not responding"
![IMG_1477](https://github.com/user-attachments/assets/0984cd21-2dbb-41e1-a5ac-221bbc82f61c)
.
I tried with two different supported ESP32 devices and the issue is the same.
As anyone encountered the same issue ?

I tried on iOS 17.5 and iOS 18.0 beta devices.

**Comment by yassik31** [comment]
Same problem for me

**Comment by davidgrdm** [comment]
Okay, in case someone have the same issue : HomePod is causing the issue. Unplugged it, so the Apple TV is the hub, reflashed and everything works perfectly :).

**Comment by Antti** [comment]
I don't have a HomePod, but still have the same issue. I have to restart Apple TV for it to start working.
Clearly, it's not a HomePod or Apple TV is causing the issue, it's a problem somewhere in this software (most likely in Homespan).
