### ISSUE TITLE
No response in HomeKit and Webinterface after about 20 Minutes

### ISSUE THREAD

**Issue by DrmedAllel** [rednblkx/HomeKey-ESP32#99]
I installed all software, wired everything up and it worked like a charm!
But after about 20 minutes the lock shows no response in the HomeKit app. Web Interface is not reachable as well. 
LEDs on the ESP and NFC module are still on. ESP is also still connected to the local wifi...

Please help.
![IMG_92DC380CA799-1](https://github.com/user-attachments/assets/fb8ca1b2-919a-4eee-ae5e-d1fff52c8deb)
<img width="2556" alt="image" src="https://github.com/user-attachments/assets/721f48bf-1d11-4ef4-9b8a-89cff15da968">

**Comment by rednblkx** [comment]
See #98
